### ISSUE TITLE
Add PHP 7.1 support

### ISSUE THREAD

**Issue by bodiski** [craftyclicks/m2-ukpostcodelookup#1]
Currently the latest php version the module requires is php7.0
Please add support for php 7.1 as this is now the latest version magento 2.2 supports.

**Comment by styloa** [comment]
The UK postcode lookup extension for Magento2 is now in [this repo](https://github.com/craftyclicks/magento2-ukpostcodelookup). PHP7.x compatibility is now correctly specified in the package.
